# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{medie}
  s.version = "1.0.0.beta3"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guilherme Silveira"]
  s.date = %q{2011-01-04}
  s.description = %q{A gem that allows you register media types and unmarshal/marshal data accordingly}
  s.email = %q{guilherme.silveira@caelum.com.br}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/medie.rb",
    "lib/medie/form_url_encoded.rb",
    "lib/medie/form_url_encoded/driver.rb",
    "lib/medie/generic.rb",
    "lib/medie/json.rb",
    "lib/medie/json/driver.rb",
    "lib/medie/json/links.rb",
    "lib/medie/link.rb",
    "lib/medie/linked.rb",
    "lib/medie/open_search.rb",
    "lib/medie/open_search/descriptor.rb",
    "lib/medie/open_search/driver.rb",
    "lib/medie/registry.rb",
    "lib/medie/xml.rb",
    "lib/medie/xml/driver.rb",
    "lib/medie/xml/links.rb",
    "spec/integration/full_json.js",
    "spec/integration/json_spec.rb",
    "spec/medie/json/driver_spec.rb",
    "spec/medie/linked/form_url_encoded/driver_spec.rb",
    "spec/medie/linked/open_search/descriptor_spec.rb",
    "spec/medie/registry_spec.rb",
    "spec/medie/xml/driver_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/Guilherme Silveira/medie}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A gem that allows you register media types and unmarshal/marshal data accordingly}
  s.test_files = [
    "spec/integration/json_spec.rb",
    "spec/medie/json/driver_spec.rb",
    "spec/medie/linked/form_url_encoded/driver_spec.rb",
    "spec/medie/linked/open_search/descriptor_spec.rb",
    "spec/medie/registry_spec.rb",
    "spec/medie/xml/driver_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<methodize>, [">= 0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<actionpack>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<methodize>, [">= 0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<actionpack>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<methodize>, [">= 0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<actionpack>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

